name: Dev Deploy to s3
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Deploy to s3
        env: 
            AWS_DEFAULT_REGION: us-east-1 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          aws s3 cp . s3://li-permit-tracker-dev --region us-east-1 --recursive # change it
